apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: openshift-sandboxed-containers-monitor
  name: metrics
spec:
  ports:
  - name: metrics
    port: 8090
    protocol: TCP
    targetPort: 0
  selector:
    name: openshift-sandboxed-containers-monitor
status:
  loadBalancer: {}
